#!/bin/busybox sh
set -efu

busybox mkdir -p /sbin /usr/bin /usr/sbin
/bin/busybox --install -s

mkdir -p /run /var/log /tmp

mkdir /proc
mount -t proc none /proc
mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts none /dev/pts

mkdir -p /root/.ssh
chmod 700 /root/.ssh
echo "root:x:0:0:root:/root:/bin/sh" >/etc/passwd

ID_RSA_PUB=$(awk -v RS=' ' '/^id_rsa_pub=/ { print }' /proc/cmdline | sed -e 's/^[^=]*=//')
printf "ssh-rsa %s\n" "$ID_RSA_PUB" >>/root/.ssh/authorized_keys

ip link set lo up
ip link set eth0 up
start-stop-daemon -S -p /run/udhcpc.eth0.pid -x /bin/sh -b -- -c "exec >/var/log/udhcpc.eth0.log 2>&1; exec udhcpc -i eth0 -s /etc/udhcpc/default.script -f"

/etc/init.d/syslogd start
/etc/init.d/dropbear start

echo "Boot time: $(busybox cat /proc/uptime)"
